# Generated by Django 5.0.6 on 2024-06-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AddField(
            model_name='budget',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
