# Generated by Django 5.0.6 on 2024-06-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.UUIDField()),
                ("expense_type_id", models.IntegerField()),
                ("category_id", models.IntegerField()),
                ("bankcard_id", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
