# Generated by Django 5.0.6 on 2024-06-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("user_expense_type", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.UUIDField()),
                ("bankcard_id", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="categories.category")),
                (
                    "user_expense_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_expense_type.userexpensetype"
                    ),
                ),
            ],
        ),
    ]
