# Generated by Django 5.0.6 on 2024-06-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
