# Generated by Django 5.0.6 on 2024-07-01 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_expense_bankcard_id_alter_expense_username"),
        ("expenses", "0002_expense_description"),
    ]

    operations = []
