# Generated by Django 5.0.6 on 2024-07-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_merge_20240701_2317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="username",
            field=models.UUIDField(),
        ),
    ]
