# Generated by Django 5.0.6 on 2024-06-06 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 6, 4, 3, 44, 102325)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
