# Generated by Django 5.0.6 on 2024-06-06 04:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_created_at_user_enabled_user_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="uuid",
            new_name="user_id",
        ),
    ]
