# Generated by Django 5.0.6 on 2024-06-30 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account_number", models.IntegerField()),
                ("bank_name", models.CharField(max_length=128)),
                ("card_type", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field="user_id"
                    ),
                ),
            ],
        ),
    ]
