# Generated by Django 5.0.6 on 2024-06-20 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piggies", "0002_alter_piggies_piggy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="piggies",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
        ),
    ]
