# Generated by Django 5.0.6 on 2024-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserExpenseType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.UUIDField()),
                ("name", models.CharField(default="Personal", max_length=70)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("set_by_user", models.BooleanField(default=False)),
                ("category_name", models.CharField(max_length=70)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
