# Generated by Django 5.0.6 on 2024-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_expense_type", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexpensetype",
            name="set_by_user",
            field=models.BooleanField(default=True),
        ),
    ]
